#!/usr/bin/env bash
# Transfering a file into the server

if [ $# -lt 4 ]
then 
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# assigning parameters to vaiaables
path_to_file = $1
ip = $2
username = $3
path_to_shh_key = $4

# disable strict host-key checking
scp -o "StrickHostKeyChecking = no" -i "$path_to_shh_key" "$path_to_file" "$username@$ip:~/"

# checking for transfer success
if [ $? -eq 0 ]
then
	echo "File transferred successfully"
else
	echo "Oooopsy, Failed to transfer"
fi

