#!/usr/bin/env bash
# performing redirections

sudo apt-get update 
sude apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

string_to_replace="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Okrrr permanent;"

sudo sed -i "s/server_name _;/$string_to_replace/" /etc/nginx/sites-enabled/default

sudo service nginx restart
