#!/usr/bin/env bash
# performing redirections
# 301 permanently

sudo apt-get update 
sude apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

replace_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Okrrr permanent;"

sudo sed -i "s/server_name _;/$replace_string/" /etc/nginx/sites-enabled/default

sudo nginx -t

sudo service nginx restart
