#!/usr/bin/env bash
# 404-error_page

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

# Performing a "moved permanently redirection" (301)
replace_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Okrrr permanent;"
sudo sed -i "s/server_name _;/$replace_string/" /etc/nginx/sites-enabled/default

# Creating a 404 Custom error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
replace_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$replace_string/" /etc/nginx/sites-enabled/default

sudo service nginx restart
