#!/usr/bin/env bash
# Script to install and configure HAProxy on lb-01 server
# Configuring HAProxy to send traffic to web-01 and web-02 servers
# Distributing requests using a roundrobin algorithm
# Ensuring that HAProxy can be managed via an init script

# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  Okrrr_frontend
        bind *:80
        mode http
        default_backend Okrrr_backend
backend Okrrr_backend
        balance roundrobin
        server 474015-web-01 52.91.120.72:80 check
        server 474015-web-02 35.153.50.234:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Testing the HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

sudo service haproxy restart
